-- 用户蛐蛐表增加个体属性字段
ALTER TABLE user_crickets
  ADD COLUMN IF NOT EXISTS attack       INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS defense      INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS speed        INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS max_hp       INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS max_stamina  INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS spirit_base  INTEGER NOT NULL DEFAULT 100;
